### ISSUE TITLE
Porkbun API is transionning to api.porkbun.com

### ISSUE THREAD

**Issue by The-Young-Maker** [jadolg/porkbun-ddns#65]
Hi, I just received an email from porkbun saying that their api is now on api.porkbun.com . Have you already changed it? 
![image](https://github.com/user-attachments/assets/d94fbef8-798d-458e-bed5-abafeb87638f)

**Comment by jadolg** [comment]
We use github.com/nrdcg/porkbun to communicate with porkbun and they have already updated back in June https://github.com/nrdcg/porkbun/commit/b87518cc5512a15751f6834dd700a2555119f9f5
