### ISSUE TITLE
Allow modifying the root domain

### ISSUE THREAD

**Issue by jadolg** [jadolg/porkbun-ddns#9]
Right now the `host` field is mandatory in a record but this should not be the case if the root domain is the target for the update.

**Comment by Nomar383** [comment]
It seems to update the root domain name without issue, but I still get this error message in the logs right after a root domain update:

time="2023-09-22T02:44:50Z" level=error msg="status: 400 message: {\"status\":\"ERROR\",\"message\":\"Create error: We were unable to create the DNS record.\"}"

**Comment by jadolg** [comment]
I found the problem and have a solution on the way
